### ISSUE TITLE
Text not cropping when is longest as the card size

### ISSUE THREAD

**Issue by holic-cl** [vue-bulma/card#2]
Hi, i was using the card component on my project and i found this problem when text is longest as the card size, i think text should be cropped but is exceding the card size.

![screenshot-area-2017-04-19-165537](https://cloud.githubusercontent.com/assets/4250401/25199631/da994ada-2521-11e7-90b0-40ab61541256.png)

I don't know how to lead with this problem. Any workarround or suggestion, i will appretiate.

**Comment by luventa** [comment]
Hi @holic-cl 
The class `is-fullwidth` of Bulma is set on card item in BaseCard as default. 
So the workaround is to adjust the width of the component container. 

For example:
```html
<div class="YOUR CLASS" style="width: 400px;(put this into your css)">
  <base-card>...</base-card>
</div>
```
